// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS5alN0XMgU9ofvrCxEDqtryX4Ghq6OIo',
    appId: '1:436590148667:web:16a0215d002a334f80701e',
    messagingSenderId: '436590148667',
    projectId: 'dailyrecords-85331',
    authDomain: 'dailyrecords-85331.firebaseapp.com',
    storageBucket: 'dailyrecords-85331.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGH9soCZUa-WHsys6DgRaNljOD746ACLg',
    appId: '1:436590148667:android:ebae58aef6e1d59b80701e',
    messagingSenderId: '436590148667',
    projectId: 'dailyrecords-85331',
    storageBucket: 'dailyrecords-85331.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXLWOaDWRQHrt6VEF4o6WCI53PpzcIdrU',
    appId: '1:436590148667:ios:63f8ee3fb4d1ae2980701e',
    messagingSenderId: '436590148667',
    projectId: 'dailyrecords-85331',
    storageBucket: 'dailyrecords-85331.appspot.com',
    iosClientId: '436590148667-pp9fod19qt9gd1rf66n2k95f1qu11a1d.apps.googleusercontent.com',
    iosBundleId: 'org.tenant.tenant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXLWOaDWRQHrt6VEF4o6WCI53PpzcIdrU',
    appId: '1:436590148667:ios:63f8ee3fb4d1ae2980701e',
    messagingSenderId: '436590148667',
    projectId: 'dailyrecords-85331',
    storageBucket: 'dailyrecords-85331.appspot.com',
    iosClientId: '436590148667-pp9fod19qt9gd1rf66n2k95f1qu11a1d.apps.googleusercontent.com',
    iosBundleId: 'org.tenant.tenant',
  );
}
